version: 0.2

phases:
    install:
        runtime-versions:
            java: openjdk11
    build:
        commands:
            - mvn -B package
            - docker build -f src/main/docker/Dockerfile.jvm -t user-directory-api-jvm .
    post_build:
        commands:
            - echo "Finished, TODO - push docker image"

