version: 0.2

phases:
    install:
        runtime-versions:
            java: openjdk11
    pre_build:
        commands:
            - echo Logging in to Amazon ECR....
            - aws --version
            - $(aws ecr get-login --no-include-email --region $AWS_REGION)
    build:
        commands:
            - mvn -B package
            - docker build -f src/main/docker/Dockerfile.jvm -t user-dir-api .
    post_build:
        commands:
            - echo "Pushing docker image"
            - docker tag user-dir-api:latest 535376556962.dkr.ecr.eu-west-1.amazonaws.com/user-dir-api:latest
            - docker push 535376556962.dkr.ecr.eu-west-1.amazonaws.com/user-dir-api:latest

