version: "3"

services:
  database:
    container_name: ${POSTGRES_HOST}
    image: postgres:12-alpine
    ports:
    - 5432:5432
    env_file:
      - .env
  api:
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
      context: ./
    depends_on:
      - database
    ports:
    - 8080:8080
    env_file:
      - .env
