version: 0.2
env:
    variables:
        IMAGE_URI: "535376556962.dkr.ecr.eu-west-1.amazonaws.com/user-dir-api:latest"
phases:
    install:
        runtime-versions:
            java: openjdk11
    pre_build:
        commands:
            - echo Logging in to Amazon ECR....
            - aws --version
            - $(aws ecr get-login --no-include-email --region $AWS_REGION)
    build:
        commands:
            - mvn -B package
            - docker build -f src/main/docker/Dockerfile.jvm -t user-dir-api .
    post_build:
        commands:
            - echo "Pushing docker image"
            - docker tag user-dir-api:latest $IMAGE_URI
            - docker push $IMAGE_URI
            - printf '{"Parameters":{"ServiceName":"user-api","ImageUrl":"%s"}}' $IMAGE_URI > fargateStackConfig.json

artifacts:
    files: fargateStackConfig.json
